name: Test Installing wxmplot with conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python with Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        python-version: ${{ matrix.python-version }}
    - name: Install conda and dependencies
      run: |
        conda update -n base -c defaults conda
        conda config --set always_yes true --set changeps1 true
        conda config --add channels conda-forge
        conda install python=${{ matrix.python-version }} numpy matplotlib pip pytest
        conda install wxpython
        conda info -a
        conda list
    - name: Install wxmplot with pip
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Test with pytest
      run: |
        cd tests
        pytest
