name: Test Installing wxmplot with conda

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install conda and dependencies
      run: |
        conda install numpy matplotlib pytest pip
        conda list
        conda install -y -c conda-forge wxpython
        conda info
        conda list
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wxutils
    - name: Test with pytest
      run: |
        python setup.py install
        cd tests
        pytest
